import type {
  EndpointParameter,
  EndpointSummary,
  RequestBodySummary,
  ResponseSummary,
  SchemaDetails,
  SecuritySchemeSummary,
} from "./openapi";
import type { SchemaModel, SchemaModelProperty } from "./schema-models";
import type { Language } from "./translations";

export type HtmlDocumentationOptions = {
  includeDeprecated?: boolean;
  includeExamples?: boolean;
  includeModels?: boolean;
  language?: Language;
};

export type HtmlDocumentationBuild = {
  html: string;
  summary: {
    deprecatedExcludedCount: number;
    endpointCount: number;
    methodCount: number;
    modelCount: number;
    securitySchemeCount: number;
  };
};

type DocumentationLabels = {
  allMethods: string;
  authentication: string;
  contentTypes: string;
  cookie: string;
  deprecated: string;
  description: string;
  documentation: string;
  empty: string;
  endpointCount: string;
  endpoints: string;
  enum: string;
  example: string;
  format: string;
  generatedBy: string;
  header: string;
  in: string;
  methodCount: string;
  methodFilter: string;
  modelCount: string;
  models: string;
  name: string;
  noDescription: string;
  noResponses: string;
  optional: string;
  parameters: string;
  path: string;
  properties: string;
  publicAccess: string;
  query: string;
  requestBody: string;
  required: string;
  responseHeaders: string;
  responses: string;
  resultCount: string;
  schema: string;
  search: string;
  searchPlaceholder: string;
  security: string;
  securityCount: string;
  server: string;
  status: string;
  switchTheme: string;
  tags: string;
  type: string;
  usage: string;
  version: string;
};

const labelsByLanguage: Record<Language, DocumentationLabels> = {
  en: {
    allMethods: "All methods",
    authentication: "Authentication",
    contentTypes: "Content types",
    cookie: "Cookie",
    deprecated: "Deprecated",
    description: "Description",
    documentation: "API documentation",
    empty: "No endpoints match the current filters.",
    endpointCount: "Endpoints",
    endpoints: "Endpoints",
    enum: "Allowed values",
    example: "Example",
    format: "Format",
    generatedBy: "Generated by RSSwag",
    header: "Header",
    in: "In",
    methodCount: "Methods",
    methodFilter: "Filter by method",
    modelCount: "Models",
    models: "Schema models",
    name: "Name",
    noDescription: "No description provided.",
    noResponses: "No responses documented.",
    optional: "Optional",
    parameters: "Parameters",
    path: "Path",
    properties: "Properties",
    publicAccess: "Public access",
    query: "Query",
    requestBody: "Request body",
    required: "Required",
    responseHeaders: "Response headers",
    responses: "Responses",
    resultCount: "{visible} of {total} endpoints",
    schema: "Schema",
    search: "Search documentation",
    searchPlaceholder: "Path, summary, tag, or ID",
    security: "Security schemes",
    securityCount: "Auth schemes",
    server: "Server",
    status: "Status",
    switchTheme: "Switch color theme",
    tags: "Tags",
    type: "Type",
    usage: "Used by",
    version: "Version",
  },
  ru: {
    allMethods: "Все методы",
    authentication: "Аутентификация",
    contentTypes: "Типы содержимого",
    cookie: "Cookie",
    deprecated: "Устарел",
    description: "Описание",
    documentation: "Документация API",
    empty: "Нет эндпоинтов, соответствующих фильтрам.",
    endpointCount: "Эндпоинты",
    endpoints: "Эндпоинты",
    enum: "Допустимые значения",
    example: "Пример",
    format: "Формат",
    generatedBy: "Создано в RSSwag",
    header: "Заголовок",
    in: "Где",
    methodCount: "Методы",
    methodFilter: "Фильтр по методу",
    modelCount: "Модели",
    models: "Модели схемы",
    name: "Имя",
    noDescription: "Описание отсутствует.",
    noResponses: "Ответы не документированы.",
    optional: "Необязательно",
    parameters: "Параметры",
    path: "Путь",
    properties: "Свойства",
    publicAccess: "Публичный доступ",
    query: "Query",
    requestBody: "Тело запроса",
    required: "Обязательно",
    responseHeaders: "Заголовки ответа",
    responses: "Ответы",
    resultCount: "Эндпоинты: {visible} из {total}",
    schema: "Схема",
    search: "Поиск по документации",
    searchPlaceholder: "Путь, описание, тег или ID",
    security: "Схемы безопасности",
    securityCount: "Схемы доступа",
    server: "Сервер",
    status: "Статус",
    switchTheme: "Переключить цветовую тему",
    tags: "Теги",
    type: "Тип",
    usage: "Используется в",
    version: "Версия",
  },
};

function escapeHtml(value: unknown) {
  return String(value ?? "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

function renderText(value: string, fallback: string) {
  const text = value.trim() || fallback;
  return escapeHtml(text);
}

function getOperationKey(method: string, path: string) {
  return `${method.toUpperCase()} ${path}`;
}

function getRelatedModels(endpoints: EndpointSummary[], models: SchemaModel[]) {
  const operationKeys = new Set(
    endpoints.map((endpoint) =>
      getOperationKey(endpoint.method, endpoint.path),
    ),
  );
  const modelsByName = new Map(models.map((model) => [model.name, model]));
  const selectedNames = new Set<string>();
  const queue = models
    .filter((model) =>
      model.usages.some((usage) =>
        operationKeys.has(getOperationKey(usage.method, usage.path)),
      ),
    )
    .map((model) => model.name);

  while (queue.length > 0) {
    const name = queue.shift();

    if (!name || selectedNames.has(name)) continue;
    selectedNames.add(name);

    const model = modelsByName.get(name);
    model?.references.forEach((reference) => {
      if (modelsByName.has(reference) && !selectedNames.has(reference)) {
        queue.push(reference);
      }
    });
  }

  return models.filter((model) => selectedNames.has(model.name));
}

function getRelatedSecuritySchemes(
  endpoints: EndpointSummary[],
  securitySchemes: SecuritySchemeSummary[],
) {
  const names = new Set(
    endpoints.flatMap((endpoint) => endpoint.securityRequirements),
  );
  return securitySchemes.filter((scheme) => names.has(scheme.name));
}

function getParameterLocationLabel(
  location: EndpointParameter["location"],
  labels: DocumentationLabels,
) {
  return {
    cookie: labels.cookie,
    header: labels.header,
    path: labels.path,
    query: labels.query,
  }[location];
}

function getParameterConstraints(parameter: EndpointParameter) {
  const constraints = [
    parameter.enumValues?.length
      ? `enum: ${parameter.enumValues.join(", ")}`
      : "",
    parameter.minimum !== undefined ? `min: ${parameter.minimum}` : "",
    parameter.maximum !== undefined ? `max: ${parameter.maximum}` : "",
    parameter.minLength !== undefined
      ? `minLength: ${parameter.minLength}`
      : "",
    parameter.maxLength !== undefined
      ? `maxLength: ${parameter.maxLength}`
      : "",
    parameter.pattern ? `pattern: ${parameter.pattern}` : "",
  ].filter(Boolean);

  return constraints.join("; ");
}

function renderExample(example: string, labels: DocumentationLabels) {
  if (!example.trim()) return "";

  return `<div class="example"><p class="detail-label">${escapeHtml(labels.example)}</p><pre><code>${escapeHtml(example)}</code></pre></div>`;
}

function renderSchemaSummary(
  schema: SchemaDetails,
  labels: DocumentationLabels,
  includeExamples: boolean,
) {
  const properties = schema.properties.length
    ? `<p class="schema-properties"><strong>${escapeHtml(labels.properties)}:</strong> ${escapeHtml(schema.properties.join(", "))}</p>`
    : "";
  const example = includeExamples ? renderExample(schema.example, labels) : "";

  return `<div class="schema-summary">
    <p><strong>${escapeHtml(labels.schema)}:</strong> <code>${escapeHtml(schema.type || "unknown")}</code></p>
    ${properties}
    ${example}
  </div>`;
}

function renderParameters(
  parameters: EndpointParameter[],
  labels: DocumentationLabels,
  includeExamples: boolean,
) {
  if (parameters.length === 0) return "";

  const rows = parameters
    .map((parameter) => {
      const constraints = getParameterConstraints(parameter);

      return `<tr>
        <td><code>${escapeHtml(parameter.name)}</code></td>
        <td>${escapeHtml(getParameterLocationLabel(parameter.location, labels))}</td>
        <td><code>${escapeHtml(parameter.type || "string")}</code></td>
        <td>${escapeHtml(parameter.required ? labels.required : labels.optional)}</td>
        <td>${renderText(parameter.description, labels.noDescription)}</td>
        ${includeExamples ? `<td><code>${escapeHtml(parameter.example)}</code></td>` : ""}
        <td>${escapeHtml(constraints || "-")}</td>
      </tr>`;
    })
    .join("");

  return `<section class="contract-block">
    <h4>${escapeHtml(labels.parameters)}</h4>
    <div class="table-wrap"><table>
      <thead><tr>
        <th>${escapeHtml(labels.name)}</th>
        <th>${escapeHtml(labels.in)}</th>
        <th>${escapeHtml(labels.type)}</th>
        <th>${escapeHtml(labels.status)}</th>
        <th>${escapeHtml(labels.description)}</th>
        ${includeExamples ? `<th>${escapeHtml(labels.example)}</th>` : ""}
        <th>${escapeHtml(labels.format)}</th>
      </tr></thead>
      <tbody>${rows}</tbody>
    </table></div>
  </section>`;
}

function renderRequestBody(
  body: RequestBodySummary,
  index: number,
  labels: DocumentationLabels,
  includeExamples: boolean,
) {
  return `<div class="contract-item">
    <div class="contract-heading">
      <code>${escapeHtml(body.contentType || `body-${index + 1}`)}</code>
      <span class="chip">${escapeHtml(body.required ? labels.required : labels.optional)}</span>
    </div>
    ${body.description ? `<p>${escapeHtml(body.description)}</p>` : ""}
    ${renderSchemaSummary(body.schema, labels, includeExamples)}
  </div>`;
}

function renderRequestBodies(
  bodies: RequestBodySummary[],
  labels: DocumentationLabels,
  includeExamples: boolean,
) {
  if (bodies.length === 0) return "";

  return `<section class="contract-block">
    <h4>${escapeHtml(labels.requestBody)}</h4>
    ${bodies
      .map((body, index) =>
        renderRequestBody(body, index, labels, includeExamples),
      )
      .join("")}
  </section>`;
}

function renderResponse(
  response: ResponseSummary,
  labels: DocumentationLabels,
  includeExamples: boolean,
) {
  const headers = response.headers?.length
    ? `<div class="response-headers">
        <p class="detail-label">${escapeHtml(labels.responseHeaders)}</p>
        <ul>${response.headers
          .map(
            (header) =>
              `<li><code>${escapeHtml(header.name)}</code>${header.description ? ` - ${escapeHtml(header.description)}` : ""}</li>`,
          )
          .join("")}</ul>
      </div>`
    : "";
  const contentTypes = response.contentTypes.length
    ? `<p><strong>${escapeHtml(labels.contentTypes)}:</strong> ${escapeHtml(response.contentTypes.join(", "))}</p>`
    : "";
  const schema = response.schema
    ? renderSchemaSummary(response.schema, labels, includeExamples)
    : "";

  return `<div class="contract-item response-item">
    <div class="contract-heading">
      <span class="status-code">${escapeHtml(response.status)}</span>
      <strong>${renderText(response.description, labels.noDescription)}</strong>
    </div>
    ${contentTypes}
    ${headers}
    ${schema}
  </div>`;
}

function renderResponses(
  responses: ResponseSummary[],
  labels: DocumentationLabels,
  includeExamples: boolean,
) {
  return `<section class="contract-block">
    <h4>${escapeHtml(labels.responses)}</h4>
    ${
      responses.length
        ? responses
            .map((response) =>
              renderResponse(response, labels, includeExamples),
            )
            .join("")
        : `<p class="muted">${escapeHtml(labels.noResponses)}</p>`
    }
  </section>`;
}

function renderSecurityRequirement(
  endpoint: EndpointSummary,
  labels: DocumentationLabels,
) {
  if (!endpoint.secured) {
    return `<span class="chip public">${escapeHtml(labels.publicAccess)}</span>`;
  }

  const groups = endpoint.securityRequirementGroups?.length
    ? endpoint.securityRequirementGroups
        .map((group) => group.join(" + "))
        .join(" / ")
    : endpoint.securityRequirements.join(", ");

  return `<span class="chip secured">${escapeHtml(labels.authentication)}: ${escapeHtml(groups)}</span>`;
}

function renderEndpoint(
  endpoint: EndpointSummary,
  index: number,
  labels: DocumentationLabels,
  includeExamples: boolean,
) {
  const id = `operation-${index + 1}`;
  const method = endpoint.method.toUpperCase();
  const heading =
    endpoint.summary || endpoint.operationId || `${method} ${endpoint.path}`;
  const searchText = [
    method,
    endpoint.path,
    endpoint.summary,
    endpoint.description,
    endpoint.operationId,
    ...endpoint.tags,
    ...endpoint.securityRequirements,
  ]
    .join(" ")
    .toLowerCase();
  const tags = endpoint.tags.length
    ? `<div class="chips"><span class="detail-label">${escapeHtml(labels.tags)}</span>${endpoint.tags
        .map((tag) => `<span class="chip">${escapeHtml(tag)}</span>`)
        .join("")}</div>`
    : "";

  return {
    article: `<article class="endpoint" data-endpoint data-method="${escapeHtml(method)}" data-search="${escapeHtml(searchText)}" id="${id}">
      <header class="endpoint-heading">
        <span class="method method-${escapeHtml(method.toLowerCase())}">${escapeHtml(method)}</span>
        <div class="endpoint-title">
          <h3>${escapeHtml(heading)}</h3>
          <code>${escapeHtml(endpoint.path)}</code>
        </div>
      </header>
      <div class="chips">
        ${renderSecurityRequirement(endpoint, labels)}
        ${endpoint.deprecated ? `<span class="chip deprecated">${escapeHtml(labels.deprecated)}</span>` : ""}
        ${endpoint.operationId ? `<span class="chip"><code>${escapeHtml(endpoint.operationId)}</code></span>` : ""}
      </div>
      ${tags}
      ${endpoint.description ? `<p class="endpoint-description">${escapeHtml(endpoint.description)}</p>` : ""}
      ${renderParameters(endpoint.parameters, labels, includeExamples)}
      ${renderRequestBodies(endpoint.requestBodies, labels, includeExamples)}
      ${renderResponses(endpoint.responses, labels, includeExamples)}
    </article>`,
    id,
    label: `${method} ${endpoint.path}`,
    method,
    searchText,
  };
}

function renderModelProperty(
  property: SchemaModelProperty,
  labels: DocumentationLabels,
) {
  const details = [
    property.format ? `${labels.format}: ${property.format}` : "",
    property.enumValues.length
      ? `${labels.enum}: ${property.enumValues.join(", ")}`
      : "",
    property.nullable ? "nullable" : "",
    property.readOnly ? "readOnly" : "",
    property.writeOnly ? "writeOnly" : "",
    property.deprecated ? labels.deprecated : "",
  ].filter(Boolean);

  return `<tr>
    <td><code>${escapeHtml(property.name)}</code></td>
    <td><code>${escapeHtml(property.type)}</code></td>
    <td>${escapeHtml(property.required ? labels.required : labels.optional)}</td>
    <td>${renderText(property.description, labels.noDescription)}</td>
    <td>${escapeHtml(details.join("; ") || "-")}</td>
  </tr>`;
}

function renderModel(
  model: SchemaModel,
  labels: DocumentationLabels,
  includeExamples: boolean,
) {
  const usage = model.usages.length
    ? `<p><strong>${escapeHtml(labels.usage)}:</strong> ${model.usages
        .map(
          (item) =>
            `<code>${escapeHtml(`${item.method.toUpperCase()} ${item.path}`)}</code>`,
        )
        .join(", ")}</p>`
    : "";
  const properties = model.properties.length
    ? `<div class="table-wrap"><table>
        <thead><tr>
          <th>${escapeHtml(labels.name)}</th>
          <th>${escapeHtml(labels.type)}</th>
          <th>${escapeHtml(labels.status)}</th>
          <th>${escapeHtml(labels.description)}</th>
          <th>${escapeHtml(labels.format)}</th>
        </tr></thead>
        <tbody>${model.properties
          .map((property) => renderModelProperty(property, labels))
          .join("")}</tbody>
      </table></div>`
    : "";

  return `<article class="model" id="model-${escapeHtml(model.name.toLowerCase().replace(/[^a-z0-9]+/g, "-"))}">
    <header class="model-heading">
      <h3>${escapeHtml(model.name)}</h3>
      <code>${escapeHtml(model.type)}</code>
      ${model.deprecated ? `<span class="chip deprecated">${escapeHtml(labels.deprecated)}</span>` : ""}
    </header>
    ${model.description ? `<p>${escapeHtml(model.description)}</p>` : ""}
    ${usage}
    ${properties}
    <div class="example"><p class="detail-label">TypeScript</p><pre><code>${escapeHtml(model.typeScript)}</code></pre></div>
    ${includeExamples ? renderExample(model.example, labels) : ""}
  </article>`;
}

function renderSecurityScheme(scheme: SecuritySchemeSummary) {
  const details = [
    scheme.scheme,
    scheme.bearerFormat,
    scheme.parameterName,
    scheme.location,
  ].filter(Boolean);

  return `<article class="security-scheme">
    <div><h3>${escapeHtml(scheme.name)}</h3><code>${escapeHtml(scheme.type)}</code></div>
    ${details.length ? `<p>${escapeHtml(details.join(" · "))}</p>` : ""}
    ${scheme.description ? `<p>${escapeHtml(scheme.description)}</p>` : ""}
  </article>`;
}

function renderDocument({
  endpoints,
  includeExamples,
  labels,
  language,
  models,
  schema,
  securitySchemes,
}: {
  endpoints: EndpointSummary[];
  includeExamples: boolean;
  labels: DocumentationLabels;
  language: Language;
  models: SchemaModel[];
  schema: { serverUrl: string; title: string; version: string };
  securitySchemes: SecuritySchemeSummary[];
}) {
  const renderedEndpoints = endpoints.map((endpoint, index) =>
    renderEndpoint(endpoint, index, labels, includeExamples),
  );
  const methods = [
    ...new Set(renderedEndpoints.map((item) => item.method)),
  ].sort();
  const title = schema.title.trim() || "OpenAPI";
  const resultTemplate = labels.resultCount
    .replace("{visible}", String(endpoints.length))
    .replace("{total}", String(endpoints.length));

  return `<!doctype html>
<html lang="${escapeHtml(language)}" data-theme="light">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="generator" content="RSSwag">
  <title>${escapeHtml(title)} - ${escapeHtml(labels.documentation)}</title>
  <script>try{var savedTheme=localStorage.getItem("rsswag-docs-theme");if(savedTheme==="dark"||(!savedTheme&&matchMedia("(prefers-color-scheme: dark)").matches)){document.documentElement.dataset.theme="dark"}}catch(error){}</script>
  <style>
    :root { color-scheme: light; --bg: #f7f8fb; --surface: #fff; --surface-2: #f0f2f7; --text: #11162f; --muted: #596174; --border: #d9ddeb; --accent: #5a2dff; --accent-soft: #eeeaff; --success: #08775c; --danger: #b42318; --code: #171a25; --code-text: #edf1ff; }
    :root[data-theme="dark"] { color-scheme: dark; --bg: #12141b; --surface: #1a1d27; --surface-2: #242834; --text: #f3f5fb; --muted: #aeb6c7; --border: #383e4d; --accent: #aa92ff; --accent-soft: #302852; --success: #66dab9; --danger: #ff8d85; --code: #0c0e13; --code-text: #edf1ff; }
    * { box-sizing: border-box; }
    html { scroll-behavior: smooth; }
    body { margin: 0; background: var(--bg); color: var(--text); font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; line-height: 1.55; letter-spacing: 0; }
    button, input, select { font: inherit; letter-spacing: 0; }
    button, input, select { border: 1px solid var(--border); border-radius: 6px; background: var(--surface); color: var(--text); }
    button:focus-visible, input:focus-visible, select:focus-visible, a:focus-visible { outline: 3px solid color-mix(in srgb, var(--accent) 35%, transparent); outline-offset: 2px; }
    a { color: inherit; }
    code { font-family: "SFMono-Regular", Consolas, "Liberation Mono", monospace; overflow-wrap: anywhere; }
    .topbar { border-bottom: 1px solid var(--border); background: var(--surface); }
    .topbar-inner { max-width: 1500px; margin: 0 auto; padding: 28px 32px; display: flex; align-items: flex-start; justify-content: space-between; gap: 24px; }
    .eyebrow { margin: 0 0 4px; color: var(--accent); font-size: 12px; font-weight: 800; text-transform: uppercase; }
    h1, h2, h3, h4, p { overflow-wrap: anywhere; }
    h1 { margin: 0; font-size: 30px; line-height: 1.2; }
    .subtitle { margin: 8px 0 0; color: var(--muted); }
    .theme-button { width: 42px; height: 42px; flex: 0 0 42px; cursor: pointer; font-size: 22px; }
    .summary { border-bottom: 1px solid var(--border); background: var(--surface); }
    .summary-grid { max-width: 1500px; margin: 0 auto; padding: 0 32px; display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); }
    .stat { min-width: 0; padding: 18px 20px; border-left: 1px solid var(--border); }
    .stat:last-child { border-right: 1px solid var(--border); }
    .stat span { display: block; color: var(--muted); font-size: 12px; font-weight: 700; }
    .stat strong { display: block; margin-top: 2px; font-size: 24px; }
    .shell { width: min(1500px, 100%); margin: 0 auto; padding: 28px 32px 56px; display: grid; grid-template-columns: 280px minmax(0, 1fr); gap: 32px; align-items: start; }
    .sidebar { position: sticky; top: 20px; min-width: 0; max-height: calc(100vh - 40px); overflow: auto; border-right: 1px solid var(--border); padding-right: 24px; }
    .control { display: grid; gap: 6px; margin-bottom: 14px; color: var(--muted); font-size: 12px; font-weight: 700; }
    .control input, .control select { width: 100%; min-width: 0; height: 42px; padding: 0 11px; font-size: 14px; }
    .result-count { margin: 12px 0; color: var(--muted); font-size: 13px; font-weight: 700; }
    .nav-title { margin: 22px 0 8px; font-size: 13px; }
    .endpoint-nav { margin: 0; padding: 0; list-style: none; }
    .endpoint-nav li { border-top: 1px solid var(--border); }
    .endpoint-nav a { display: block; padding: 9px 4px; text-decoration: none; font-family: "SFMono-Regular", Consolas, monospace; font-size: 12px; overflow-wrap: anywhere; }
    .endpoint-nav a:hover { color: var(--accent); }
    .content { min-width: 0; }
    .content > h2 { margin: 0 0 12px; font-size: 23px; }
    .endpoint, .model, .security-scheme { scroll-margin-top: 20px; border-top: 1px solid var(--border); padding: 26px 0; }
    .endpoint:last-child, .model:last-child { border-bottom: 1px solid var(--border); }
    .endpoint-heading { display: flex; align-items: flex-start; gap: 14px; min-width: 0; }
    .endpoint-title { min-width: 0; }
    .endpoint-title h3, .model h3, .security-scheme h3 { margin: 0; font-size: 18px; }
    .endpoint-title > code { display: block; margin-top: 3px; color: var(--muted); font-size: 14px; }
    .method { flex: 0 0 64px; padding: 5px 7px; border-radius: 4px; text-align: center; font: 800 12px/1.3 "SFMono-Regular", Consolas, monospace; }
    .method-get { background: #d8f6e9; color: #08684f; } .method-post { background: #dff2ff; color: #075d8c; } .method-put { background: #eee7ff; color: #5930a4; } .method-patch { background: #fff0c9; color: #805600; } .method-delete { background: #ffe2df; color: #a1261c; } .method-head, .method-options, .method-trace { background: #e7e9ef; color: #3f4655; }
    .chips { display: flex; flex-wrap: wrap; align-items: center; gap: 7px; margin-top: 14px; }
    .chip { display: inline-flex; max-width: 100%; align-items: center; border-radius: 4px; background: var(--surface-2); padding: 3px 7px; color: var(--muted); font-size: 12px; font-weight: 700; overflow-wrap: anywhere; }
    .chip.secured { background: var(--accent-soft); color: var(--accent); } .chip.public { color: var(--success); } .chip.deprecated { color: var(--danger); }
    .detail-label { margin: 0; color: var(--muted); font-size: 11px; font-weight: 800; text-transform: uppercase; }
    .endpoint-description { margin: 16px 0 0; white-space: pre-wrap; }
    .contract-block { margin-top: 24px; }
    .contract-block h4 { margin: 0 0 10px; font-size: 15px; }
    .contract-item { border-left: 3px solid var(--border); padding: 8px 0 8px 14px; margin-top: 10px; }
    .contract-heading, .model-heading, .security-scheme > div { display: flex; flex-wrap: wrap; align-items: center; gap: 10px; min-width: 0; }
    .contract-heading > strong { min-width: 0; }
    .status-code { border-radius: 4px; background: var(--surface-2); padding: 3px 8px; font-family: "SFMono-Regular", Consolas, monospace; font-weight: 800; }
    .schema-summary p, .contract-item p, .model p, .security-scheme p { margin: 8px 0 0; }
    .table-wrap { width: 100%; overflow-x: auto; border: 1px solid var(--border); border-radius: 6px; }
    table { width: 100%; min-width: 680px; border-collapse: collapse; font-size: 13px; }
    th, td { padding: 10px 12px; border-bottom: 1px solid var(--border); text-align: left; vertical-align: top; }
    th { background: var(--surface-2); color: var(--muted); font-size: 11px; text-transform: uppercase; }
    tbody tr:last-child td { border-bottom: 0; }
    .example { margin-top: 12px; }
    pre { max-height: 360px; overflow: auto; margin: 6px 0 0; border-radius: 6px; background: var(--code); padding: 14px; color: var(--code-text); font-size: 12px; line-height: 1.6; white-space: pre-wrap; overflow-wrap: anywhere; }
    .models-section, .security-section { margin-top: 46px; }
    .model-heading > code { color: var(--muted); }
    .security-scheme { display: grid; grid-template-columns: minmax(180px, .7fr) minmax(0, 1fr) minmax(0, 1.4fr); gap: 20px; }
    .security-scheme p { margin: 0; }
    .empty { border: 1px dashed var(--border); border-radius: 6px; padding: 28px; color: var(--muted); text-align: center; }
    .muted { color: var(--muted); }
    footer { border-top: 1px solid var(--border); padding: 20px 32px; color: var(--muted); text-align: center; font-size: 12px; }
    [hidden] { display: none !important; }
    @media (max-width: 800px) {
      .topbar-inner { padding: 22px 18px; } h1 { font-size: 25px; }
      .summary-grid { padding: 0 18px; grid-template-columns: repeat(2, minmax(0, 1fr)); }
      .stat:nth-child(3) { border-top: 1px solid var(--border); } .stat:nth-child(4) { border-top: 1px solid var(--border); }
      .shell { padding: 22px 18px 42px; grid-template-columns: minmax(0, 1fr); gap: 28px; }
      .sidebar { position: static; max-height: none; border-right: 0; border-bottom: 1px solid var(--border); padding: 0 0 20px; }
      .endpoint-nav { display: flex; gap: 8px; overflow-x: auto; padding-bottom: 6px; }
      .endpoint-nav li { flex: 0 0 min(270px, 78vw); border: 1px solid var(--border); border-radius: 6px; }
      .endpoint-nav a { padding: 9px; }
      .security-scheme { grid-template-columns: minmax(0, 1fr); gap: 6px; }
    }
    @media print {
      :root { color-scheme: light; --bg: #fff; --surface: #fff; --surface-2: #f4f4f4; --text: #000; --muted: #444; --border: #bbb; }
      .theme-button, .sidebar { display: none; } .shell { display: block; padding: 20px; } .endpoint, .model { break-inside: avoid; } pre { max-height: none; }
    }
  </style>
</head>
<body>
  <header class="topbar">
    <div class="topbar-inner">
      <div>
        <p class="eyebrow">${escapeHtml(labels.documentation)}</p>
        <h1>${escapeHtml(title)}</h1>
        <p class="subtitle">${escapeHtml(labels.version)} ${escapeHtml(schema.version || "-")} · ${escapeHtml(labels.server)} <code>${escapeHtml(schema.serverUrl || "-")}</code></p>
      </div>
      <button class="theme-button" id="theme-toggle" type="button" aria-label="${escapeHtml(labels.switchTheme)}" title="${escapeHtml(labels.switchTheme)}"><span aria-hidden="true">◐</span></button>
    </div>
  </header>
  <section class="summary" aria-label="Summary">
    <div class="summary-grid">
      <div class="stat"><span>${escapeHtml(labels.endpointCount)}</span><strong>${endpoints.length}</strong></div>
      <div class="stat"><span>${escapeHtml(labels.methodCount)}</span><strong>${methods.length}</strong></div>
      <div class="stat"><span>${escapeHtml(labels.modelCount)}</span><strong>${models.length}</strong></div>
      <div class="stat"><span>${escapeHtml(labels.securityCount)}</span><strong>${securitySchemes.length}</strong></div>
    </div>
  </section>
  <div class="shell">
    <aside class="sidebar">
      <label class="control" for="docs-search">${escapeHtml(labels.search)}<input id="docs-search" type="search" placeholder="${escapeHtml(labels.searchPlaceholder)}" autocomplete="off"></label>
      <label class="control" for="method-filter">${escapeHtml(labels.methodFilter)}<select id="method-filter"><option value="all">${escapeHtml(labels.allMethods)}</option>${methods.map((method) => `<option value="${escapeHtml(method)}">${escapeHtml(method)}</option>`).join("")}</select></label>
      <p class="result-count" data-result-template="${escapeHtml(labels.resultCount)}" id="result-count">${escapeHtml(resultTemplate)}</p>
      <h2 class="nav-title">${escapeHtml(labels.endpoints)}</h2>
      <nav aria-label="${escapeHtml(labels.endpoints)}"><ol class="endpoint-nav">${renderedEndpoints
        .map(
          (endpoint) =>
            `<li data-nav-item data-method="${escapeHtml(endpoint.method)}" data-search="${escapeHtml(endpoint.searchText)}"><a href="#${endpoint.id}">${escapeHtml(endpoint.label)}</a></li>`,
        )
        .join("")}</ol></nav>
    </aside>
    <main class="content">
      <h2>${escapeHtml(labels.endpoints)}</h2>
      <div id="empty-state" class="empty" hidden>${escapeHtml(labels.empty)}</div>
      <div id="endpoint-list">${renderedEndpoints.map((endpoint) => endpoint.article).join("")}</div>
      ${
        securitySchemes.length
          ? `<section class="security-section"><h2>${escapeHtml(labels.security)}</h2>${securitySchemes.map(renderSecurityScheme).join("")}</section>`
          : ""
      }
      ${
        models.length
          ? `<section class="models-section"><h2>${escapeHtml(labels.models)}</h2>${models.map((model) => renderModel(model, labels, includeExamples)).join("")}</section>`
          : ""
      }
    </main>
  </div>
  <footer>${escapeHtml(labels.generatedBy)}</footer>
  <script>
    (function () {
      var search = document.getElementById("docs-search");
      var method = document.getElementById("method-filter");
      var endpoints = Array.prototype.slice.call(document.querySelectorAll("[data-endpoint]"));
      var navItems = Array.prototype.slice.call(document.querySelectorAll("[data-nav-item]"));
      var count = document.getElementById("result-count");
      var empty = document.getElementById("empty-state");
      var themeButton = document.getElementById("theme-toggle");
      function update() {
        var query = search.value.trim().toLowerCase();
        var selectedMethod = method.value;
        var visible = 0;
        endpoints.forEach(function (endpoint) {
          var matches = (selectedMethod === "all" || endpoint.dataset.method === selectedMethod) && (!query || endpoint.dataset.search.indexOf(query) !== -1);
          endpoint.hidden = !matches;
          if (matches) visible += 1;
        });
        navItems.forEach(function (item) {
          item.hidden = !((selectedMethod === "all" || item.dataset.method === selectedMethod) && (!query || item.dataset.search.indexOf(query) !== -1));
        });
        count.textContent = count.dataset.resultTemplate.replace("{visible}", String(visible)).replace("{total}", String(endpoints.length));
        empty.hidden = visible !== 0;
      }
      search.addEventListener("input", update);
      method.addEventListener("change", update);
      themeButton.addEventListener("click", function () {
        var next = document.documentElement.dataset.theme === "dark" ? "light" : "dark";
        document.documentElement.dataset.theme = next;
        try { localStorage.setItem("rsswag-docs-theme", next); } catch (error) {}
      });
      update();
    })();
  </script>
</body>
</html>`;
}

export function createHtmlDocumentation(
  endpoints: EndpointSummary[],
  models: SchemaModel[],
  securitySchemes: SecuritySchemeSummary[],
  schema: { serverUrl: string; title: string; version: string },
  options: HtmlDocumentationOptions = {},
): HtmlDocumentationBuild {
  const includeDeprecated = options.includeDeprecated ?? true;
  const includeExamples = options.includeExamples ?? true;
  const includeModels = options.includeModels ?? true;
  const language = options.language ?? "en";
  const selectedEndpoints = includeDeprecated
    ? endpoints
    : endpoints.filter((endpoint) => !endpoint.deprecated);
  const selectedModels = includeModels
    ? getRelatedModels(selectedEndpoints, models)
    : [];
  const selectedSecuritySchemes = getRelatedSecuritySchemes(
    selectedEndpoints,
    securitySchemes,
  );

  return {
    html: renderDocument({
      endpoints: selectedEndpoints,
      includeExamples,
      labels: labelsByLanguage[language],
      language,
      models: selectedModels,
      schema,
      securitySchemes: selectedSecuritySchemes,
    }),
    summary: {
      deprecatedExcludedCount: includeDeprecated
        ? 0
        : endpoints.length - selectedEndpoints.length,
      endpointCount: selectedEndpoints.length,
      methodCount: new Set(
        selectedEndpoints.map((endpoint) => endpoint.method.toUpperCase()),
      ).size,
      modelCount: selectedModels.length,
      securitySchemeCount: selectedSecuritySchemes.length,
    },
  };
}
