import type { EndpointParameter, EndpointSummary } from "./openapi";
import { createSchemaMockResponse } from "./request-mock";

export type NodeMockServerOptions = {
  cors?: boolean;
  defaultDelayMs?: number;
  defaultPort?: number;
  includeDeprecated?: boolean;
  validateRequiredInputs?: boolean;
};

export type NodeMockServerRoute = {
  bodyVariantCount: number;
  defaultStatus: number;
  deprecated: boolean;
  method: string;
  path: string;
  responseStatuses: string[];
};

export type NodeMockServerBuild = {
  routes: NodeMockServerRoute[];
  source: string;
  summary: {
    bodyVariantCount: number;
    deprecatedExcludedCount: number;
    responseVariantCount: number;
    routeCount: number;
  };
};

type SerializedParameter = Pick<
  EndpointParameter,
  "location" | "name" | "required"
>;

type SerializedResponse = {
  body: string;
  headers: Record<string, string>;
  key: string;
  status: number;
};

type SerializedRoute = {
  deprecated: boolean;
  method: string;
  operationId: string;
  parameters: SerializedParameter[];
  path: string;
  requestBodyRequired: boolean;
  responses: SerializedResponse[];
  summary: string;
};

const MAX_DELAY_MS = 30_000;
const DEFAULT_PORT = 4_010;

function clampInteger(
  value: number | undefined,
  fallback: number,
  minimum: number,
  maximum: number,
) {
  if (!Number.isFinite(value)) return fallback;
  return Math.min(maximum, Math.max(minimum, Math.round(value ?? fallback)));
}

function normalizePath(path: string) {
  const normalized = path.trim();
  if (!normalized) return "/";
  return normalized.startsWith("/") ? normalized : `/${normalized}`;
}

function normalizeStatus(status: string) {
  const value = Number(status);
  return Number.isInteger(value) && value >= 200 && value <= 599 ? value : 200;
}

function sanitizeResponseHeaders(headers: Record<string, string>) {
  return Object.fromEntries(
    Object.entries(headers)
      .filter(([name]) => /^[!#$%&'*+.^_`|~0-9A-Za-z-]+$/.test(name))
      .map(([name, value]) => [name, value.replace(/[\r\n]+/g, " ").trim()]),
  );
}

function createFallbackResponse(endpoint: EndpointSummary): SerializedResponse {
  return {
    body: JSON.stringify(
      {
        message: `Mock response for ${endpoint.method.toUpperCase()} ${endpoint.path}`,
      },
      null,
      2,
    ),
    headers: { "content-type": "application/json; charset=utf-8" },
    key: "default",
    status: 200,
  };
}

function serializeResponses(endpoint: EndpointSummary) {
  const responses = endpoint.responses.map((response) => {
    const mock = createSchemaMockResponse(response, "");

    return {
      body: mock.body,
      headers: sanitizeResponseHeaders(mock.headers),
      key: response.status || mock.status,
      status: normalizeStatus(mock.status),
    } satisfies SerializedResponse;
  });

  return responses.length > 0 ? responses : [createFallbackResponse(endpoint)];
}

function getDefaultResponse(responses: SerializedResponse[]) {
  return (
    responses.find(
      (response) => response.status >= 200 && response.status < 300,
    ) ?? responses[0]
  );
}

function serializeRoute(endpoint: EndpointSummary): SerializedRoute {
  return {
    deprecated: endpoint.deprecated,
    method: endpoint.method.toUpperCase(),
    operationId: endpoint.operationId,
    parameters: endpoint.parameters.map((parameter) => ({
      location: parameter.location,
      name: parameter.name,
      required: parameter.required,
    })),
    path: normalizePath(endpoint.path),
    requestBodyRequired: endpoint.requestBodies.some((body) => body.required),
    responses: serializeResponses(endpoint),
    summary: endpoint.summary,
  };
}

function serializeForJavaScript(value: unknown) {
  return JSON.stringify(value, null, 2)
    .replaceAll("<", "\\u003c")
    .replaceAll("\u2028", "\\u2028")
    .replaceAll("\u2029", "\\u2029");
}

function createRuntimeSource({
  cors,
  defaultDelayMs,
  defaultPort,
  routes,
  schema,
  validateRequiredInputs,
}: {
  cors: boolean;
  defaultDelayMs: number;
  defaultPort: number;
  routes: SerializedRoute[];
  schema: { title: string; version: string };
  validateRequiredInputs: boolean;
}) {
  return `// Generated by RSSwag. This file has no package dependencies.
// Run with: node mock-server.mjs
// Optional environment variables: PORT and MOCK_DELAY_MS.
// Per request: ?__status=404 selects a documented response and ?__delay=250 adds latency.
// Metadata: GET /__rsswag/health and GET /__rsswag/routes.
import { createServer } from "node:http";
import { pathToFileURL } from "node:url";

const schema = ${serializeForJavaScript({
    title: schema.title,
    version: schema.version,
  })};
const routeDefinitions = ${serializeForJavaScript(routes)};
const generatedDefaults = ${serializeForJavaScript({
    cors,
    defaultDelayMs,
    defaultPort,
    validateRequiredInputs,
  })};
const MAX_BODY_BYTES = 1024 * 1024;
const MAX_DELAY_MS = 30000;

function escapeRegularExpression(value) {
  const specialCharacters = "\\\\^$.*+?()[]{}|";
  return Array.from(value, (character) =>
    specialCharacters.includes(character) ? "\\\\" + character : character,
  ).join("");
}

function compilePath(path) {
  const names = [];
  const matcher = /\\{([^}]+)\\}/g;
  let cursor = 0;
  let pattern = "^";
  let match;

  while ((match = matcher.exec(path))) {
    pattern += escapeRegularExpression(path.slice(cursor, match.index));
    pattern += "([^/]+)";
    names.push(match[1]);
    cursor = match.index + match[0].length;
  }

  pattern += escapeRegularExpression(path.slice(cursor));
  pattern += "/?$";
  return { names, regularExpression: new RegExp(pattern) };
}

const compiledRoutes = routeDefinitions.map((route) => ({
  ...route,
  compiledPath: compilePath(route.path),
}));

function safeDecode(value) {
  try {
    return decodeURIComponent(value);
  } catch {
    return value;
  }
}

export function matchRoute(method, pathname) {
  const normalizedMethod = String(method || "GET").toUpperCase();

  for (const route of compiledRoutes) {
    if (route.method !== normalizedMethod) continue;
    const match = route.compiledPath.regularExpression.exec(pathname);
    if (!match) continue;

    return {
      parameters: Object.fromEntries(
        route.compiledPath.names.map((name, index) => [
          name,
          safeDecode(match[index + 1]),
        ]),
      ),
      route,
    };
  }

  return null;
}

function parseCookies(value) {
  return String(value || "")
    .split(";")
    .map((item) => item.trim())
    .filter(Boolean)
    .reduce((cookies, item) => {
      const separator = item.indexOf("=");
      const name = separator >= 0 ? item.slice(0, separator).trim() : item;
      const rawValue = separator >= 0 ? item.slice(separator + 1).trim() : "";
      if (name) cookies[name] = safeDecode(rawValue);
      return cookies;
    }, Object.create(null));
}

function getMissingRequiredInputs(route, request, url, body) {
  const cookies = parseCookies(request.headers.cookie);

  return route.parameters.flatMap((parameter) => {
    if (!parameter.required || parameter.location === "path") return [];

    if (parameter.location === "query") {
      return url.searchParams.getAll(parameter.name).some((value) => value !== "")
        ? []
        : ["query:" + parameter.name];
    }

    if (parameter.location === "header") {
      const value = request.headers[parameter.name.toLowerCase()];
      return value !== undefined && String(value).trim() ? [] : ["header:" + parameter.name];
    }

    return cookies[parameter.name] ? [] : ["cookie:" + parameter.name];
  }).concat(route.requestBodyRequired && !body.trim() ? ["body"] : []);
}

function readRequestBody(request) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    let byteCount = 0;
    let tooLarge = false;

    request.on("data", (chunk) => {
      byteCount += chunk.length;
      if (byteCount > MAX_BODY_BYTES) {
        tooLarge = true;
        return;
      }
      chunks.push(chunk);
    });
    request.on("end", () => {
      if (tooLarge) {
        const error = new Error("Request body exceeds 1 MiB.");
        error.statusCode = 413;
        reject(error);
        return;
      }
      resolve(Buffer.concat(chunks).toString("utf8"));
    });
    request.on("error", reject);
  });
}

function getNumber(value, fallback, minimum, maximum) {
  const parsed = Number(value);
  return Number.isFinite(parsed)
    ? Math.min(maximum, Math.max(minimum, Math.round(parsed)))
    : fallback;
}

function getDelay(url, fallback) {
  const requestedDelay = url.searchParams.get("__delay");
  return getNumber(
    requestedDelay === null ? process.env.MOCK_DELAY_MS : requestedDelay,
    fallback,
    0,
    MAX_DELAY_MS,
  );
}

function selectResponse(route, requestedStatus) {
  if (!requestedStatus) {
    return route.responses.find(
      (response) => response.status >= 200 && response.status < 300,
    ) || route.responses[0];
  }

  const normalized = requestedStatus.toLowerCase();
  return route.responses.find(
    (response) =>
      response.key.toLowerCase() === normalized ||
      String(response.status) === normalized,
  );
}

function applyCors(response, enabled) {
  if (!enabled) return;
  response.setHeader("access-control-allow-origin", "*");
  response.setHeader(
    "access-control-allow-methods",
    Array.from(new Set(routeDefinitions.map((route) => route.method).concat("OPTIONS"))).join(", "),
  );
  response.setHeader("access-control-allow-headers", "content-type, authorization, x-api-key");
}

function sendJson(response, status, payload, cors) {
  response.statusCode = status;
  response.setHeader("content-type", "application/json; charset=utf-8");
  applyCors(response, cors);
  response.end(JSON.stringify(payload, null, 2));
}

function wait(delay) {
  return delay > 0
    ? new Promise((resolve) => setTimeout(resolve, delay))
    : Promise.resolve();
}

export const routes = routeDefinitions.map((route) => ({
  deprecated: route.deprecated,
  method: route.method,
  operationId: route.operationId,
  path: route.path,
  statuses: route.responses.map((response) => response.key),
  summary: route.summary,
}));

export function createMockServer(runtimeOptions = {}) {
  const cors = runtimeOptions.cors ?? generatedDefaults.cors;
  const defaultDelayMs = getNumber(
    runtimeOptions.defaultDelayMs,
    generatedDefaults.defaultDelayMs,
    0,
    MAX_DELAY_MS,
  );
  const validateRequiredInputs =
    runtimeOptions.validateRequiredInputs ?? generatedDefaults.validateRequiredInputs;
  const quiet = Boolean(runtimeOptions.quiet);

  return createServer(async (request, response) => {
    try {
      const method = String(request.method || "GET").toUpperCase();
      const url = new URL(request.url || "/", "http://localhost");
      const match = matchRoute(method, url.pathname);

      if (
        method === "OPTIONS" &&
        cors &&
        request.headers["access-control-request-method"]
      ) {
        response.statusCode = 204;
        applyCors(response, true);
        response.end();
        return;
      }

      if (!match && method === "GET" && url.pathname === "/__rsswag/health") {
        sendJson(response, 200, { ok: true, schema }, cors);
        return;
      }

      if (!match && method === "GET" && url.pathname === "/__rsswag/routes") {
        sendJson(response, 200, { routes, schema }, cors);
        return;
      }

      if (!match) {
        sendJson(response, 404, { error: "No mock route matched.", method, path: url.pathname }, cors);
        return;
      }

      const body = await readRequestBody(request);
      if (validateRequiredInputs) {
        const missing = getMissingRequiredInputs(match.route, request, url, body);
        if (missing.length > 0) {
          sendJson(response, 400, { error: "Required request inputs are missing.", missing }, cors);
          return;
        }
      }

      const selectedResponse = selectResponse(
        match.route,
        url.searchParams.get("__status"),
      );
      if (!selectedResponse) {
        sendJson(
          response,
          400,
          {
            availableStatuses: match.route.responses.map((item) => item.key),
            error: "Requested mock status is not documented.",
          },
          cors,
        );
        return;
      }

      await wait(getDelay(url, defaultDelayMs));
      response.statusCode = selectedResponse.status;
      Object.entries(selectedResponse.headers).forEach(([name, value]) =>
        response.setHeader(name, value),
      );
      applyCors(response, cors);
      const suppressBody =
        method === "HEAD" ||
        selectedResponse.status === 204 ||
        selectedResponse.status === 304;
      response.end(suppressBody ? undefined : selectedResponse.body);

      if (!quiet) {
        console.log(
          new Date().toISOString(),
          method,
          url.pathname,
          selectedResponse.status,
        );
      }
    } catch (error) {
      if (!response.headersSent) {
        sendJson(
          response,
          Number(error?.statusCode) || 500,
          { error: error instanceof Error ? error.message : "Mock server error." },
          cors,
        );
      } else {
        response.end();
      }
    }
  });
}

export function startMockServer(runtimeOptions = {}) {
  const port = getNumber(
    runtimeOptions.port ?? process.env.PORT,
    generatedDefaults.defaultPort,
    1,
    65535,
  );
  const server = createMockServer(runtimeOptions);
  server.listen(port, () => {
    console.log("RSSwag mock server listening on http://localhost:" + port);
    console.log("Loaded " + routes.length + " routes from " + schema.title + " " + schema.version + ".");
  });
  return server;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  startMockServer();
}
`;
}

export function createNodeMockServer(
  endpoints: EndpointSummary[],
  schema: { title: string; version: string },
  options: NodeMockServerOptions = {},
): NodeMockServerBuild {
  const includeDeprecated = options.includeDeprecated ?? true;
  const selectedEndpoints = includeDeprecated
    ? endpoints
    : endpoints.filter((endpoint) => !endpoint.deprecated);
  const serializedRoutes = selectedEndpoints.map(serializeRoute);
  const routes = serializedRoutes.map((route) => {
    const defaultResponse = getDefaultResponse(route.responses);

    return {
      bodyVariantCount: route.responses.filter((response) => response.body)
        .length,
      defaultStatus: defaultResponse.status,
      deprecated: route.deprecated,
      method: route.method,
      path: route.path,
      responseStatuses: route.responses.map((response) => response.key),
    };
  });

  return {
    routes,
    source: createRuntimeSource({
      cors: options.cors ?? true,
      defaultDelayMs: clampInteger(options.defaultDelayMs, 0, 0, MAX_DELAY_MS),
      defaultPort: clampInteger(options.defaultPort, DEFAULT_PORT, 1, 65_535),
      routes: serializedRoutes,
      schema,
      validateRequiredInputs: options.validateRequiredInputs ?? true,
    }),
    summary: {
      bodyVariantCount: routes.reduce(
        (total, route) => total + route.bodyVariantCount,
        0,
      ),
      deprecatedExcludedCount: includeDeprecated
        ? 0
        : endpoints.length - selectedEndpoints.length,
      responseVariantCount: routes.reduce(
        (total, route) => total + route.responseStatuses.length,
        0,
      ),
      routeCount: routes.length,
    },
  };
}
