import { describe, expect, it } from "vitest";
import type { PostmanCollectionBuild } from "./postman-collection";
import {
  createPostmanCollectionExport,
  createPostmanEnvironment,
  createPostmanEnvironmentExport,
} from "./postman-export";

const build: PostmanCollectionBuild = {
  collection: {
    info: {
      description: "Generated by RSSwag",
      name: "Catalog API",
      schema:
        "https://schema.getpostman.com/json/collection/v2.1.0/collection.json",
    },
    item: [],
    variable: [
      { key: "baseUrl", type: "string", value: "https://api.example.com" },
      { key: "bearerAuthToken", type: "string", value: "" },
    ],
  },
  secretVariableKeys: ["bearerAuthToken"],
  summary: {
    folderCount: 0,
    requestCount: 0,
    responseExampleCount: 0,
    variableCount: 2,
  },
};

describe("Postman exports", () => {
  it("creates a deterministic Collection 2.1 JSON download", () => {
    const result = createPostmanCollectionExport(
      build,
      { title: "Catalog API" },
      new Date("2026-09-01T09:30:00.000Z"),
    );

    expect(result).toMatchObject({
      contentType: "application/json",
      fileName: "rsswag-catalog-api-postman-collection-2026-09-01.json",
    });
    expect(JSON.parse(result.content)).toEqual(build.collection);
  });

  it("creates a matching environment and marks auth variables as secrets", () => {
    const environment = createPostmanEnvironment(
      build,
      { title: "Catalog API" },
      new Date("2026-09-01T09:30:00.000Z"),
    );

    expect(environment).toEqual({
      _postman_exported_at: "2026-09-01T09:30:00.000Z",
      _postman_exported_using: "RSSwag",
      _postman_variable_scope: "environment",
      name: "Catalog API - RSSwag",
      values: [
        {
          enabled: true,
          key: "baseUrl",
          type: "default",
          value: "https://api.example.com",
        },
        {
          enabled: true,
          key: "bearerAuthToken",
          type: "secret",
          value: "",
        },
      ],
    });
  });

  it("uses stable fallbacks for empty titles and invalid dates", () => {
    const result = createPostmanEnvironmentExport(
      build,
      { title: "" },
      new Date(Number.NaN),
    );

    expect(result.fileName).toBe(
      "rsswag-openapi-schema-postman-environment-1970-01-01.json",
    );
    expect(JSON.parse(result.content)).toMatchObject({
      _postman_exported_at: "1970-01-01T00:00:00.000Z",
      name: "OpenAPI Schema - RSSwag",
    });
  });
});
