import type { EndpointSummary } from "./openapi";
import { getSchemaDownloadMetadata } from "./schema-download";
import { SMOKE_TEST_RUNTIME } from "./smoke-test-runtime";

export type SmokeTestOptions = {
  includeDeprecated?: boolean;
  checkJson?: boolean;
  timeoutMs?: number;
  maxDurationMs?: number | null;
};
export type SmokeTestBuild = {
  source: string;
  config: string;
  scriptFileName: string;
  configFileName: string;
  operations: {
    key: string;
    method: string;
    path: string;
    requiredInputs: number;
    secured: boolean;
  }[];
  excludedCount: number;
};

function bounded(
  value: number | undefined,
  fallback: number,
  min: number,
  max: number,
) {
  return Number.isFinite(value)
    ? Math.max(min, Math.min(max, Math.round(value!)))
    : fallback;
}

export function createSmokeTestExport(
  endpoints: EndpointSummary[],
  title: string,
  options: SmokeTestOptions = {},
): SmokeTestBuild {
  const seen = new Set<string>();
  const selected = endpoints.filter((endpoint) => {
    const key = endpoint.method.toUpperCase() + " " + endpoint.path;
    if (
      !["GET", "HEAD"].includes(endpoint.method.toUpperCase()) ||
      (endpoint.deprecated && options.includeDeprecated === false) ||
      seen.has(key)
    )
      return false;
    seen.add(key);
    return true;
  });
  const timeoutMs = bounded(options.timeoutMs, 10000, 100, 120000);
  const operations = selected.map((endpoint) => ({
    key: endpoint.method.toUpperCase() + " " + endpoint.path,
    method: endpoint.method.toUpperCase(),
    path: endpoint.path,
    parameters: endpoint.parameters.map(({ name, location, required }) => ({
      name,
      location,
      required,
    })),
    responses: endpoint.responses.map((response) => ({
      status: response.status.toLowerCase(),
      content: response.contentTypes.map((contentType) => {
        const schema =
          response.schemasByContentType?.[contentType] ?? response.schema;
        return {
          mediaType: contentType.split(";", 1)[0].trim().toLowerCase(),
          type: schema?.type ?? "",
          required: schema?.requiredProperties ?? [],
        };
      }),
    })),
  }));
  const config = {
    baseUrl: "",
    timeoutMs,
    headers: {},
    operations: Object.fromEntries(
      operations.map((operation) => {
        const parameters = Object.fromEntries(
          ["path", "query", "header", "cookie"].map((location) => [
            location,
            Object.fromEntries(
              operation.parameters
                .filter(
                  (entry) =>
                    entry.location === location &&
                    (entry.required || location === "path"),
                )
                .map((entry) => [entry.name, ""]),
            ),
          ]),
        );
        for (const match of operation.path.matchAll(/\{([^{}]+)\}/g)) {
          Object.defineProperty(parameters.path, match[1], {
            value: "",
            enumerable: true,
            configurable: true,
            writable: true,
          });
        }
        return [operation.key, { enabled: true, parameters }];
      }),
    ),
  };
  const definition = JSON.stringify(
    {
      operations,
      timeoutMs,
      checkJson: options.checkJson !== false,
      maxDurationMs:
        options.maxDurationMs == null
          ? null
          : bounded(options.maxDurationMs, 1000, 1, 120000),
    },
    null,
    2,
  )
    .replaceAll("<", "\\u003c")
    .replaceAll("\u2028", "\\u2028")
    .replaceAll("\u2029", "\\u2029");
  const slug = getSchemaDownloadMetadata(title, "json").fileName.slice(0, -5);
  return {
    source:
      "// Generated by RSSwag. Requires Node.js 20+; no package dependencies.\n" +
      "// Set RSSWAG_BASE_URL and optionally RSSWAG_SMOKE_CONFIG (JSON file path).\n" +
      "// RSSWAG_HEADERS_JSON supplies runtime headers, including authentication.\n" +
      "// Run: node <this-file.mjs> > smoke-report.json\n" +
      "// Exit code: 0 only when at least one test passes and no tests fail or are blocked.\n" +
      "const definition = " +
      definition +
      ";\n" +
      SMOKE_TEST_RUNTIME,
    config: JSON.stringify(config, null, 2),
    scriptFileName: `rsswag-${slug}-smoke-tests.mjs`,
    configFileName: `rsswag-${slug}-smoke-config.json`,
    operations: operations.map((operation, index) => ({
      key: operation.key,
      method: operation.method,
      path: operation.path,
      requiredInputs: Object.values(
        config.operations[operation.key].parameters,
      ).reduce((total, values) => total + Object.keys(values).length, 0),
      secured: selected[index].secured,
    })),
    excludedCount: endpoints.length - operations.length,
  };
}
